name: Build dev and preprod for each commit

on:
   push:
      branches:
         - master
   workflow_dispatch:

jobs:
   build:
      name: Generate App Apk
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up JDK 11
           uses: actions/setup-java@v2
           with:
              java-version: 11
              distribution: "temurin"
              cache: gradle

         - name: Grant execute permission for gradlew
           run: chmod +x gradlew

         - name: Bundle 'release' with Gradle
           run: ./gradlew assembleRelease
           continue-on-error: true

         - name: Sign Android Release
           uses: r0adkll/sign-android-release@v1
           with:
              releaseDirectory: app/release
              signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
              alias: ${{ secrets.SIGNING_ALIAS }}
              keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
              keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}

         - run: echo "Build status report=${{ job.status }}."

         - name: Upload App Apk
           uses: actions/upload-artifact@v1
           with:
              name: my-apk
              path: app/release/app-release.apk

         - name: Upload to s3
           uses: wmanley/aws-s3-upload-action@v1
           with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws_region: us-east-1
              source: app/release/app-release.apk
              bucket: secure-share-apks
              destination: /secure-share-apks/${{ github.run_id }}/app-release.apk

         - name: Link To APK
           run: echo "https://s3.amazonaws.com/secure-share-apks/${{ github.run_id }}/app-release.apk"
