name: Build APK on comment

on:
   pull_request:
      types:
         - opened
   issue_comment:
      types:
         - created

jobs:
   run-action:
      runs-on: ubuntu-latest
      steps:
         - name: Check for command
           id: check-command
           run: |
              comment_body=$(jq -r .comment.body $GITHUB_EVENT_PATH)
              echo "Comment Body: $comment_body"
              if [[ "$comment_body" =~ "/build "(.+) ]]; then
                 echo "param1=${BASH_REMATCH[1]}" >> "$GITHUB_ENV"
                 echo "Command found with parameters: $param1"
              else
                 echo "Command Not Found"
              fi
           shell: bash

          - name: Send message to Slack API
            run: |
               slack_message="Your APK Link is https://secure-share-apks.s3.amazonaws.com/${{steps.S3.outputs.object_key}}/${{param1}}"
               echo "::set-output name=slack_message::$slack_message"
            id: notify 

         - name: Send message to Slack API
           uses: archive/github-actions-slack@v2.0.0
           id: notify
           with:
              slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
              slack-channel: app
              slack-text: ${{steps.notify.outputs.slack_message}}
