name: Build APK on comment

on:
   issue_comment:
      types:
         - created

jobs:
   run-action:
      if: contains(github.event.comment.body, '/build')
      runs-on: ubuntu-latest
      steps:
         - name: Check for command
           id: check-command
           run: |
              comment_body=$(jq -r .comment.body $GITHUB_EVENT_PATH)
              echo "Comment Body: $comment_body"
              if [[ "$comment_body" =~ "/build "(.+) ]]; then
                 echo "param1=${BASH_REMATCH[1]}" >> "$GITHUB_ENV"
                 echo "Command found with parameters: $param1"
              else
                 echo "Command Not Found"
                 exit 78
              fi
           shell: bash

         - name: Get PR branch
           uses: xt0rted/pull-request-comment-branch@v1
           id: comment-branch

         - name: Checkout PR branch
           uses: actions/checkout@v3
           with:
              ref: ${{ steps.comment-branch.outputs.head_ref }}

         - name: Set up JDK 11
           uses: actions/setup-java@v2
           with:
              java-version: 11
              distribution: "temurin"
              cache: gradle

         - name: Grant execute permission for gradlew
           run: chmod +x gradlew

         - name: Param1
           run: |
              echo "Param1 : $param1"
           shell: bash

         - name: APK with desired varient
           run: |
              ./gradlew :app:$param1
              apk=$(find ./app/release -name "*.apk" | grep -v -E "aligned|unsigned|signed")
              apk_file=$(basename "$apk")
              echo "apk_path=${apk}" >> "$GITHUB_ENV"
              echo "apk_file=${apk_file}" >> "$GITHUB_ENV"
              echo "file name = $apk_file"
           shell: bash

         - name: Sign Android Release
           uses: r0adkll/sign-android-release@v1
           with:
              releaseDirectory: app/release
              signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
              alias: ${{ secrets.SIGNING_ALIAS }}
              keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
              keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}

         - name: Build Outputs for the message
           run: |
              name="${{env.apk_file}}"
              path="${{env.apk_path}}"
              VERSION_CODE=$(grep versionCode app/build.gradle | awk '{print $2}')
              VERSION_NAME=$(grep versionName app/build.gradle | awk '{print $2}')
              REPO_NAME=$(basename "${{ github.repository }}")
              echo "::set-output name=name::$name"
              echo "::set-output name=path::$path"
              echo "::set-output name=vcode::$VERSION_CODE"
              echo "::set-output name=vname::$VERSION_NAME"
              echo "::set-output name=rname::$REPO_NAME"
           id: file

         - run: echo "Build status report=${{ job.status }}."

         - name: Send message to Slack API
           uses: adrey/slack-file-upload-action@master
           with:
              token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
              channel: app
              path: ${{steps.file.outputs.path}}
              initial_comment: "${{steps.file.outputs.rname}} - ${{steps.file.outputs.name}} - ${{steps.file.outputs.vname}}"
